:: build.sh
@echo off
echo Installing dependencies...
pip install -r requirements.txt
echo Collecting static files...
python manage.py collectstatic --no-input --clear
echo Applying migrations...
python manage.py migrate
echo Seeding core questions...
python manage.py seed_questions
echo Seeding core risk profiles...
python manage.py seed_risk_profiles
echo Seeding core risk profile mappings...
python manage.py seed_risk_profile_mapping
echo Seeding funds categories...
python manage.py seed_fund_categories
echo Seeding funds...
python manage.py seed_funds
echo Build completed.