# Generated by Django 5.2 on 2025-04-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilemapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profilemapping',
            name='time_score_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemapping',
            name='time_score_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemapping',
            name='tolerance_score_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemapping',
            name='tolerance_score_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='profilemapping',
            name='time_score',
        ),
        migrations.RemoveField(
            model_name='profilemapping',
            name='tolerance_score',
        ),
    ]
