# Generated by Django 5.2 on 2025-05-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_profilemapping_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.CharField(max_length=10)),
                ('risk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.riskprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inception_date', models.DateField()),
                ('total_return_history', models.JSONField()),
                ('risk_free_rate_history', models.JSONField()),
                ('star_rating_3yr', models.IntegerField(blank=True, null=True)),
                ('star_rating_5yr', models.IntegerField(blank=True, null=True)),
                ('star_rating_10yr', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fundcategory')),
            ],
        ),
    ]
