# Generated by Django 5.2 on 2025-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='inception_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
