# Generated by Django 5.2 on 2025-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_alter_fund_inception_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='risk_free_rate_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='total_return_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
