# Generated by Django 5.2 on 2025-05-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_alter_fund_risk_free_rate_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='category',
        ),
        migrations.AddField(
            model_name='fund',
            name='categories',
            field=models.ManyToManyField(related_name='funds', to='funds.fundcategory'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fundcategory',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
