# Generated by Django 5.2 on 2025-06-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_remove_fund_category_fund_categories_alter_fund_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='inception_date',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='risk_free_rate_history',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='star_rating_10yr',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='star_rating_3yr',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='star_rating_5yr',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='total_return_history',
        ),
        migrations.AddField(
            model_name='fund',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
